### ISSUE TITLE
Discord.Net 1.0 is on the Horizon

### ISSUE THREAD

**Issue by khionu** [Seaal/disclose#18]
You should really take a look at Discord.Net 1.0. It's been a slow development, but I fear you might be doing a lot of work that will go to waste as soon as 1.0 is released. As you can tell from the commits, development has picked up pace.

https://github.com/RogueException/Discord.Net/tree/dev

**Comment by Seaal** [comment]
Thanks for the heads up :) Are there likely to be any prerelease versions going up on nuget anytime soon, so I can start to have a look/play and see how it fits into what I've currently written.

**Comment by khionu** [comment]
No real release schedule, but I'm pretty sure nothing prerelease is going on Nuget. You can clone it now, though. It's functional, and I'm using it for a bot already. Until it's mostly tested to be stable, there won't be a release.

However, I have to advocate for this new command system that 1.0 implements.... it's absolutely fantastic.

**Comment by Seaal** [comment]
Okay fair enough, I'll clone it and check it out. Thanks again for the heads up!

**Comment by khionu** [comment]
mhm
